### ISSUE TITLE
VueJS Meetup Talks

### ISSUE THREAD

**Issue by alexander-heimbuch** [javascript-in-jena/meta#5]
Ich würde euch gerne euch mein derzeitiges OpenSource Projekt, den Podlove Web Player vorstellen. Das Projekt hat sehr viele Facetten die man in einem Talk nicht abbilden kann. Deshalb würde mich interessieren was euch am meisten gefällt. Votet mit :+1 an dem jeweiligen comment :)

Links:
- [Documentation](https://docs.podlove.org/podlove-web-player)
- [Github](https://github.com/podlove/podlove-web-player)
- [CI](https://circleci.com/gh/podlove/podlove-web-player)
- [Podlove Web Player 4 – Funktionen, Architektur und Ausblick (Video)](https://www.youtube.com/watch?v=VXgaN8pSqvQ)

**Comment by alexander-heimbuch** [comment]
[1. VueJS Essentials - Applikationen mit VueJS bauen](https://jena.js.org/vuejs-presentations/essentials.html)

**Comment by alexander-heimbuch** [comment]
2. Statemanagement in VueJS mit Redux oder Vuex - Skalierbare und praktikables Store und Effektmanagement

**Comment by alexander-heimbuch** [comment]
3. Webpack 4 Deep Dive - Konfiguration von Webpack für verschiedene Environments

**Comment by alexander-heimbuch** [comment]
4. Sandboxing JavaScript - iFrames on Steroids

**Comment by alexander-heimbuch** [comment]
5. Unit Testing mit Ava

**Comment by alexander-heimbuch** [comment]
6. Integration Testing mit Cypress

**Comment by alexander-heimbuch** [comment]
7. Komplexe CI workflows mit CircleCI

**Comment by alexander-heimbuch** [comment]
8. Vuepress - Static Prerendered SPAs für Dokumentationen

**Comment by GELight** [comment]
9. Nutzen von Vue-Components im Micro-Service Umfeld >>> Modularisierung über die Grenzen der eigenen Domain hinaus.
